package dev.trashpanda.ytmp.protocol.tsgen

import dev.trashpanda.ytmp.protocol.ApiError
import dev.trashpanda.ytmp.protocol.ClientMessage
import dev.trashpanda.ytmp.protocol.CreateRoomRequest
import dev.trashpanda.ytmp.protocol.CreateRoomResponse
import dev.trashpanda.ytmp.protocol.PROTOCOL_VERSION
import dev.trashpanda.ytmp.protocol.SearchResponse
import dev.trashpanda.ytmp.protocol.ServerMessage
import kotlinx.serialization.descriptors.PolymorphicKind
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.SerialKind
import kotlinx.serialization.descriptors.StructureKind
import kotlinx.serialization.descriptors.elementDescriptors
import kotlinx.serialization.json.JsonClassDiscriminator
import java.io.File

/**
 * Writes TypeScript declarations for the protocol by walking the kotlinx.serialization
 * descriptors, so the frontend's types always match the host's JSON.
 */
class TsGenerator {
    private val declarations = LinkedHashMap<String, String>()
    private val visiting = HashSet<String>()

    /** TS name per descriptor serial name. Sealed subclasses are named `<Parent><Variant>`. */
    private val names = HashMap<String, String>()
    private val owners = HashMap<String, String>()

    fun addRoot(descriptor: SerialDescriptor) {
        typeOf(descriptor)
    }

    fun render(): String = buildString {
        appendLine("// Generated by `./gradlew :protocol:generateTs` from the Kotlin classes in protocol/.")
        appendLine("// Do not edit by hand.")
        appendLine()
        appendLine("export const PROTOCOL_VERSION = $PROTOCOL_VERSION;")
        for (declaration in declarations.values) {
            appendLine()
            append(declaration)
        }
    }

    private fun typeOf(d: SerialDescriptor): String {
        val base = when (val kind = d.kind) {
            PrimitiveKind.STRING, PrimitiveKind.CHAR -> "string"
            PrimitiveKind.BOOLEAN -> "boolean"
            is PrimitiveKind -> "number"
            StructureKind.LIST -> "${parenthesize(typeOf(d.getElementDescriptor(0)))}[]"
            StructureKind.MAP -> "Record<${typeOf(d.getElementDescriptor(0))}, ${typeOf(d.getElementDescriptor(1))}>"
            SerialKind.ENUM, StructureKind.CLASS, StructureKind.OBJECT, PolymorphicKind.SEALED -> {
                declare(d)
                nameOf(d)
            }
            else -> error("Unsupported kind $kind for ${d.serialName}")
        }
        return if (d.isNullable) "$base | null" else base
    }

    private fun declare(d: SerialDescriptor, discriminator: Pair<String, String>? = null) {
        val name = nameOf(d)
        if (name in declarations || !visiting.add(name)) return
        val text = when (d.kind) {
            SerialKind.ENUM ->
                "export type $name = ${(0 until d.elementsCount).joinToString(" | ") { "\"${d.getElementName(it)}\"" }};\n"
            PolymorphicKind.SEALED -> declareSealed(d)
            else -> declareInterface(d, discriminator)
        }
        declarations[name] = text
        visiting.remove(name)
    }

    private fun declareInterface(d: SerialDescriptor, discriminator: Pair<String, String>?): String = buildString {
        appendLine("export interface ${nameOf(d)} {")
        if (discriminator != null) appendLine("  ${discriminator.first}: \"${discriminator.second}\";")
        for (i in 0 until d.elementsCount) {
            appendLine("  ${d.getElementName(i)}: ${typeOf(d.getElementDescriptor(i))};")
        }
        appendLine("}")
    }

    private fun declareSealed(d: SerialDescriptor): String {
        val key = d.annotations.filterIsInstance<JsonClassDiscriminator>().firstOrNull()?.discriminator ?: "type"
        // Element 1 of a sealed descriptor holds one element per subclass.
        val subclasses = d.getElementDescriptor(1).elementDescriptors.toList()
        val variantNames = subclasses.map { sub ->
            names[sub.serialName] = nameOf(d) + pascalCase(sub.serialName)
            declare(sub, key to sub.serialName)
            nameOf(sub)
        }
        return "export type ${nameOf(d)} =\n${variantNames.joinToString("\n") { "  | $it" }};\n"
    }

    private fun nameOf(d: SerialDescriptor): String {
        val serialName = d.serialName.removeSuffix("?")
        val name = names[serialName] ?: serialName.substringAfterLast('.')
        val owner = owners.getOrPut(name) { serialName }
        check(owner == serialName) { "TS name clash: '$name' is used by both $owner and $serialName" }
        return name
    }

    private fun pascalCase(serialName: String) =
        serialName.split('_').joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }

    private fun parenthesize(type: String) = if ('|' in type) "($type)" else type
}

fun main(args: Array<String>) {
    val out = File(args.single())
    val generator = TsGenerator()
    generator.addRoot(ClientMessage.serializer().descriptor)
    generator.addRoot(ServerMessage.serializer().descriptor)
    generator.addRoot(CreateRoomRequest.serializer().descriptor)
    generator.addRoot(CreateRoomResponse.serializer().descriptor)
    generator.addRoot(SearchResponse.serializer().descriptor)
    generator.addRoot(ApiError.serializer().descriptor)
    out.parentFile.mkdirs()
    out.writeText(generator.render())
    println("Wrote ${out.path}")
}
