// Generated by `./gradlew :protocol:generateTs` from the Kotlin classes in protocol/.
// Do not edit by hand.

export const PROTOCOL_VERSION = 1;

export interface ArtistRef {
  id: string | null;
  name: string;
}

export interface AlbumRef {
  id: string | null;
  name: string;
}

export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

export interface Song {
  id: string;
  title: string;
  artists: ArtistRef[];
  album: AlbumRef | null;
  durationMs: number;
  thumbnails: Thumbnail[];
  explicit: boolean;
}

export type QueuePosition = "next" | "end";

export interface CommandAddSongs {
  kind: "AddSongs";
  songs: Song[];
  position: QueuePosition;
}

export interface CommandJumpTo {
  kind: "JumpTo";
  itemId: string;
}

export interface CommandMoveQueueItem {
  kind: "MoveQueueItem";
  itemId: string;
  toIndex: number;
}

export interface CommandPause {
  kind: "Pause";
}

export interface CommandPlay {
  kind: "Play";
}

export interface CommandPlayNow {
  kind: "PlayNow";
  song: Song;
}

export interface CommandPrevious {
  kind: "Previous";
}

export interface CommandRemoveQueueItem {
  kind: "RemoveQueueItem";
  itemId: string;
}

export interface CommandSeek {
  kind: "Seek";
  positionMs: number;
}

export interface CommandSetListening {
  kind: "SetListening";
  on: boolean;
}

export interface CommandSkip {
  kind: "Skip";
}

export type Command =
  | CommandAddSongs
  | CommandJumpTo
  | CommandMoveQueueItem
  | CommandPause
  | CommandPlay
  | CommandPlayNow
  | CommandPrevious
  | CommandRemoveQueueItem
  | CommandSeek
  | CommandSetListening
  | CommandSkip;

export interface ClientMessageCommand {
  type: "command";
  id: string;
  command: Command;
}

export interface ClientMessageHello {
  type: "hello";
  protocolVersion: number;
  roomCode: string;
  guestName: string;
  guestToken: string | null;
  ownerToken: string | null;
}

export interface ClientMessagePing {
  type: "ping";
  clientTime: number;
}

export interface ClientMessageRequestSnapshot {
  type: "request_snapshot";
}

export type ClientMessage =
  | ClientMessageCommand
  | ClientMessageHello
  | ClientMessagePing
  | ClientMessageRequestSnapshot;

export type QueueItemResult = "played" | "skipped";

export interface QueueItem {
  itemId: string;
  song: Song;
  addedBy: string;
  addedByName: string;
  addedAt: number;
  result: QueueItemResult | null;
}

export interface EventHistoryAppended {
  kind: "HistoryAppended";
  item: QueueItem;
}

export interface EventHistoryItemRemoved {
  kind: "HistoryItemRemoved";
  itemId: string;
}

export interface EventNotice {
  kind: "Notice";
  message: string;
}

export interface EventNowPlayingChanged {
  kind: "NowPlayingChanged";
  item: QueueItem | null;
}

export interface Participant {
  id: string;
  name: string;
  isOwner: boolean;
  online: boolean;
  listening: boolean;
}

export interface EventParticipantJoined {
  kind: "ParticipantJoined";
  participant: Participant;
}

export interface EventParticipantLeft {
  kind: "ParticipantLeft";
  participantId: string;
}

export interface EventParticipantUpdated {
  kind: "ParticipantUpdated";
  participant: Participant;
}

export interface PlaybackStatus {
  playing: boolean;
  positionMs: number;
  hostTimeMs: number;
}

export interface EventPlaybackChanged {
  kind: "PlaybackChanged";
  playback: PlaybackStatus;
}

export interface EventQueueItemMoved {
  kind: "QueueItemMoved";
  itemId: string;
  toIndex: number;
}

export interface EventQueueItemRemoved {
  kind: "QueueItemRemoved";
  itemId: string;
}

export interface EventQueueItemsAdded {
  kind: "QueueItemsAdded";
  items: QueueItem[];
  index: number;
}

export interface EventStreamReady {
  kind: "StreamReady";
  itemId: string;
  streamUrl: string;
}

export type Event =
  | EventHistoryAppended
  | EventHistoryItemRemoved
  | EventNotice
  | EventNowPlayingChanged
  | EventParticipantJoined
  | EventParticipantLeft
  | EventParticipantUpdated
  | EventPlaybackChanged
  | EventQueueItemMoved
  | EventQueueItemRemoved
  | EventQueueItemsAdded
  | EventStreamReady;

export interface ServerMessageEvent {
  type: "event";
  seq: number;
  event: Event;
}

export interface ServerMessagePong {
  type: "pong";
  clientTime: number;
  hostTime: number;
}

export type RejectReason = "room_not_found" | "version_mismatch" | "invalid_name" | "replaced";

export interface ServerMessageRejected {
  type: "rejected";
  reason: RejectReason;
}

export type ErrorCode = "not_found" | "invalid" | "permission_denied";

export interface ErrorInfo {
  code: ErrorCode;
  message: string;
}

export interface ServerMessageResult {
  type: "result";
  id: string;
  error: ErrorInfo | null;
}

export interface RoomInfo {
  code: string;
  name: string;
}

export interface NowPlaying {
  item: QueueItem;
  streamUrl: string | null;
}

export interface RoomState {
  room: RoomInfo;
  participants: Participant[];
  queue: QueueItem[];
  history: QueueItem[];
  nowPlaying: NowPlaying | null;
  playback: PlaybackStatus;
}

export interface ServerMessageSnapshot {
  type: "snapshot";
  seq: number;
  state: RoomState;
}

export interface ServerMessageWelcome {
  type: "welcome";
  participantId: string;
  guestToken: string;
  seq: number;
  state: RoomState;
}

export type ServerMessage =
  | ServerMessageEvent
  | ServerMessagePong
  | ServerMessageRejected
  | ServerMessageResult
  | ServerMessageSnapshot
  | ServerMessageWelcome;

export interface CreateRoomRequest {
  name: string;
}

export interface CreateRoomResponse {
  code: string;
  ownerToken: string;
}

export interface SearchResponse {
  items: Song[];
}

export interface ApiError {
  error: ErrorInfo;
}
