// Generated by `./gradlew :protocol:generateTs` from the Kotlin classes in protocol/.
// Do not edit by hand.

export const PROTOCOL_VERSION = 1;

export interface ClientMessageAttach {
  type: "attach";
  protocolVersion: number;
  roomCode: string;
  guestToken: string;
}

export interface ArtistRef {
  id: string | null;
  name: string;
}

export interface AlbumRef {
  id: string | null;
  name: string;
}

export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

export interface PodcastRef {
  id: string;
  name: string;
}

export interface Song {
  id: string;
  title: string;
  artists: ArtistRef[];
  album: AlbumRef | null;
  durationMs: number;
  thumbnails: Thumbnail[];
  explicit: boolean;
  podcast: PodcastRef | null;
}

export type QueuePosition = "next" | "end";

export interface CommandAddSongs {
  kind: "AddSongs";
  songs: Song[];
  position: QueuePosition;
}

export interface CommandAssignRole {
  kind: "AssignRole";
  participantId: string;
  roleId: string;
}

export interface CommandAutoplayFromHere {
  kind: "AutoplayFromHere";
  song: Song;
}

export interface CommandBan {
  kind: "Ban";
  participantId: string;
}

export interface CommandClearAutoplay {
  kind: "ClearAutoplay";
}

export interface CommandClearQueue {
  kind: "ClearQueue";
}

export type Permission = "add_songs" | "play_now" | "remove_own" | "remove_others" | "reorder" | "start_radio" | "autoplay_from_here" | "play_pause" | "skip" | "seek" | "listen_locally" | "change_outputs" | "output_volume" | "kick" | "ban" | "assign_roles" | "edit_roles" | "change_settings";

export interface CommandCreateRole {
  kind: "CreateRole";
  name: string;
  color: string;
  permissions: Permission[];
}

export interface CommandDeleteRole {
  kind: "DeleteRole";
  roleId: string;
}

export interface CommandJumpTo {
  kind: "JumpTo";
  itemId: string;
}

export interface CommandKick {
  kind: "Kick";
  participantId: string;
}

export type ItemList = "history" | "queue" | "autoplay";

export interface CommandMoveItem {
  kind: "MoveItem";
  itemId: string;
  list: ItemList;
  toIndex: number;
}

export interface CommandMoveQueueItem {
  kind: "MoveQueueItem";
  itemId: string;
  toIndex: number;
}

export interface CommandMoveRole {
  kind: "MoveRole";
  roleId: string;
  toIndex: number;
}

export interface CommandPause {
  kind: "Pause";
}

export interface CommandPlay {
  kind: "Play";
}

export interface CommandPlayNow {
  kind: "PlayNow";
  song: Song;
}

export interface CommandPrevious {
  kind: "Previous";
}

export interface CommandRemoveQueueItem {
  kind: "RemoveQueueItem";
  itemId: string;
}

export interface CommandSeek {
  kind: "Seek";
  positionMs: number;
}

export interface CommandSetListening {
  kind: "SetListening";
  on: boolean;
}

export interface CommandSetOutput {
  kind: "SetOutput";
  outputId: string;
  active: boolean;
}

export interface CommandSetOutputVolume {
  kind: "SetOutputVolume";
  outputId: string;
  volume: number;
}

export interface CommandSetParticipantPermissions {
  kind: "SetParticipantPermissions";
  participantId: string;
  allow: Permission[];
  deny: Permission[];
}

export type RoomVisibility = "public" | "private";

export interface CommandSetVisibility {
  kind: "SetVisibility";
  visibility: RoomVisibility;
}

export interface CommandSkip {
  kind: "Skip";
}

export interface CommandStartRadio {
  kind: "StartRadio";
  song: Song;
}

export interface CommandUnban {
  kind: "Unban";
  banId: string;
}

export interface Role {
  id: string;
  name: string;
  color: string;
  permissions: Permission[];
}

export interface CommandUpdateRole {
  kind: "UpdateRole";
  role: Role;
}

export interface CommandUpdateSettings {
  kind: "UpdateSettings";
  name: string | null;
  defaultGuestRole: string | null;
  defaultAccountRole: string | null;
  autoplay: boolean | null;
}

export type Command =
  | CommandAddSongs
  | CommandAssignRole
  | CommandAutoplayFromHere
  | CommandBan
  | CommandClearAutoplay
  | CommandClearQueue
  | CommandCreateRole
  | CommandDeleteRole
  | CommandJumpTo
  | CommandKick
  | CommandMoveItem
  | CommandMoveQueueItem
  | CommandMoveRole
  | CommandPause
  | CommandPlay
  | CommandPlayNow
  | CommandPrevious
  | CommandRemoveQueueItem
  | CommandSeek
  | CommandSetListening
  | CommandSetOutput
  | CommandSetOutputVolume
  | CommandSetParticipantPermissions
  | CommandSetVisibility
  | CommandSkip
  | CommandStartRadio
  | CommandUnban
  | CommandUpdateRole
  | CommandUpdateSettings;

export interface ClientMessageCommand {
  type: "command";
  id: string;
  command: Command;
}

export interface ClientMessageHello {
  type: "hello";
  protocolVersion: number;
  roomCode: string;
  guestName: string;
  guestToken: string | null;
  ownerToken: string | null;
  accountToken: string | null;
  hideFromHistory: boolean;
}

export interface ClientMessagePing {
  type: "ping";
  clientTime: number;
}

export interface ClientMessageRequestSnapshot {
  type: "request_snapshot";
}

export type ClientMessage =
  | ClientMessageAttach
  | ClientMessageCommand
  | ClientMessageHello
  | ClientMessagePing
  | ClientMessageRequestSnapshot;

export type QueueItemResult = "played" | "skipped";

export type QueueItemOrigin = "manual" | "radio" | "autoplay";

export interface QueueItem {
  itemId: string;
  song: Song;
  addedBy: string;
  addedByName: string;
  addedAt: number;
  result: QueueItemResult | null;
  origin: QueueItemOrigin;
}

export interface EventAutoplayChanged {
  kind: "AutoplayChanged";
  seed: Song | null;
  items: QueueItem[];
}

export interface BanInfo {
  id: string;
  name: string;
  accountId: string | null;
}

export interface EventBansChanged {
  kind: "BansChanged";
  bans: BanInfo[];
}

export interface EventHistoryAppended {
  kind: "HistoryAppended";
  item: QueueItem;
}

export interface EventHistoryItemRemoved {
  kind: "HistoryItemRemoved";
  itemId: string;
}

export interface EventHistoryReplaced {
  kind: "HistoryReplaced";
  items: QueueItem[];
}

export interface EventNotice {
  kind: "Notice";
  message: string;
}

export interface EventNowPlayingChanged {
  kind: "NowPlayingChanged";
  item: QueueItem | null;
}

export type OutputKind = "chromecast" | "sonos";

export interface OutputInfo {
  id: string;
  name: string;
  kind: OutputKind;
  active: boolean;
  volume: number | null;
}

export interface EventOutputsChanged {
  kind: "OutputsChanged";
  outputs: OutputInfo[];
}

export interface Participant {
  id: string;
  name: string;
  isOwner: boolean;
  online: boolean;
  listening: boolean;
  accountId: string | null;
  roleId: string;
  allow: Permission[];
  deny: Permission[];
}

export interface EventParticipantJoined {
  kind: "ParticipantJoined";
  participant: Participant;
}

export interface EventParticipantLeft {
  kind: "ParticipantLeft";
  participantId: string;
}

export interface EventParticipantUpdated {
  kind: "ParticipantUpdated";
  participant: Participant;
}

export interface PlaybackStatus {
  playing: boolean;
  positionMs: number;
  hostTimeMs: number;
}

export interface EventPlaybackChanged {
  kind: "PlaybackChanged";
  playback: PlaybackStatus;
}

export interface EventQueueItemMoved {
  kind: "QueueItemMoved";
  itemId: string;
  toIndex: number;
}

export interface EventQueueItemRemoved {
  kind: "QueueItemRemoved";
  itemId: string;
}

export interface EventQueueItemsAdded {
  kind: "QueueItemsAdded";
  items: QueueItem[];
  index: number;
}

export interface EventQueueReplaced {
  kind: "QueueReplaced";
  items: QueueItem[];
}

export interface EventRolesChanged {
  kind: "RolesChanged";
  roles: Role[];
}

export interface RoomInfo {
  code: string;
  name: string;
  visibility: RoomVisibility;
}

export interface EventRoomUpdated {
  kind: "RoomUpdated";
  room: RoomInfo;
}

export interface RoomSettings {
  defaultGuestRole: string;
  defaultAccountRole: string;
  autoplay: boolean;
}

export interface EventSettingsChanged {
  kind: "SettingsChanged";
  settings: RoomSettings;
}

export interface EventStreamReady {
  kind: "StreamReady";
  itemId: string;
  streamUrl: string;
}

export type Event =
  | EventAutoplayChanged
  | EventBansChanged
  | EventHistoryAppended
  | EventHistoryItemRemoved
  | EventHistoryReplaced
  | EventNotice
  | EventNowPlayingChanged
  | EventOutputsChanged
  | EventParticipantJoined
  | EventParticipantLeft
  | EventParticipantUpdated
  | EventPlaybackChanged
  | EventQueueItemMoved
  | EventQueueItemRemoved
  | EventQueueItemsAdded
  | EventQueueReplaced
  | EventRolesChanged
  | EventRoomUpdated
  | EventSettingsChanged
  | EventStreamReady;

export interface ServerMessageEvent {
  type: "event";
  seq: number;
  event: Event;
}

export interface ServerMessagePong {
  type: "pong";
  clientTime: number;
  hostTime: number;
}

export type RejectReason = "room_not_found" | "version_mismatch" | "invalid_name" | "replaced" | "private_room" | "kicked" | "banned";

export interface ServerMessageRejected {
  type: "rejected";
  reason: RejectReason;
}

export type ErrorCode = "not_found" | "invalid" | "permission_denied";

export interface ErrorInfo {
  code: ErrorCode;
  message: string;
}

export interface ServerMessageResult {
  type: "result";
  id: string;
  error: ErrorInfo | null;
}

export interface NowPlaying {
  item: QueueItem;
  streamUrl: string | null;
}

export interface RoomState {
  room: RoomInfo;
  participants: Participant[];
  queue: QueueItem[];
  history: QueueItem[];
  nowPlaying: NowPlaying | null;
  playback: PlaybackStatus;
  outputs: OutputInfo[];
  roles: Role[];
  settings: RoomSettings;
  bans: BanInfo[];
  autoplay: QueueItem[];
  autoplaySeed: Song | null;
}

export interface ServerMessageSnapshot {
  type: "snapshot";
  seq: number;
  state: RoomState;
}

export interface ServerMessageWelcome {
  type: "welcome";
  participantId: string;
  guestToken: string;
  seq: number;
  state: RoomState;
  accountId: string | null;
}

export type ServerMessage =
  | ServerMessageEvent
  | ServerMessagePong
  | ServerMessageRejected
  | ServerMessageResult
  | ServerMessageSnapshot
  | ServerMessageWelcome;

export interface CreateRoomRequest {
  name: string;
  visibility: RoomVisibility;
}

export interface CreateRoomResponse {
  code: string;
  ownerToken: string;
}

export interface SearchResponse {
  items: Song[];
}

export interface ApiError {
  error: ErrorInfo;
}

export type HostKind = "server" | "phone";

export interface AuthServerRef {
  url: string | null;
  issuer: string;
}

export interface HostInfo {
  kind: HostKind;
  shareUrl: string | null;
  canCreateRooms: boolean;
  supportsPrivateRooms: boolean;
  authServers: AuthServerRef[];
}

export interface RoomListResponse {
  rooms: RoomInfo[];
}

export type SignupMode = "open" | "invite" | "admin";

export interface AuthServerInfo {
  issuer: string;
  publicKey: string;
  signup: SignupMode;
  needsAdmin: boolean;
}

export interface AccountInfo {
  id: string;
  username: string;
  displayName: string;
  isAdmin: boolean;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface SignupRequest {
  username: string;
  password: string;
  displayName: string | null;
  invite: string | null;
}

export interface SessionResponse {
  sessionToken: string;
  account: AccountInfo;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export interface HostTokenRequest {
  origin: string;
}

export interface HostTokenResponse {
  token: string;
  expiresAt: number;
  account: AccountInfo;
}

export interface AccountListResponse {
  accounts: AccountInfo[];
}

export interface CreateAccountRequest {
  username: string;
  password: string;
  displayName: string | null;
}

export interface SetPasswordRequest {
  password: string;
}

export interface InviteResponse {
  code: string;
  expiresAt: number;
}

export interface LinkAuthServerRequest {
  url: string | null;
}

export interface RoleTemplate {
  roles: Role[];
  settings: RoomSettings;
  knownPermissions: Permission[] | null;
}

export interface ListenedWith {
  accountId: string | null;
  name: string;
}

export interface HistoryEntry {
  id: string;
  song: Song;
  playedAt: number;
  heardMs: number;
  skipped: boolean;
  roomName: string;
  addedByMe: boolean;
  addedByName: string;
  listenedWith: ListenedWith[];
  shared: boolean;
}

export interface HistoryPage {
  plays: HistoryEntry[];
  more: boolean;
}

export interface AccountSettings {
  tracking: boolean;
  hideFromOthers: boolean;
}

export interface PlayReport {
  song: Song;
  playedAt: number;
  heardMs: number;
  skipped: boolean;
  roomCode: string;
  roomName: string;
  addedByMe: boolean;
  addedByName: string;
  listenedWith: ListenedWith[];
  shared: boolean;
}

export interface AlbumSummary {
  id: string;
  title: string;
  kind: string;
  year: string | null;
  thumbnails: Thumbnail[];
}

export interface ArtistPage {
  id: string;
  name: string;
  thumbnails: Thumbnail[];
  description: string | null;
  songs: Song[];
  albums: AlbumSummary[];
  singles: AlbumSummary[];
}

export interface AlbumPage {
  id: string;
  title: string;
  kind: string;
  year: string | null;
  artists: ArtistRef[];
  thumbnails: Thumbnail[];
  songs: Song[];
}

export interface PlaylistPage {
  id: string;
  title: string;
  author: string | null;
  description: string | null;
  thumbnails: Thumbnail[];
  songs: Song[];
}

export type SearchType = "all" | "songs" | "videos" | "albums" | "artists" | "community_playlists" | "featured_playlists" | "podcasts" | "episodes";

export interface SearchItemAlbum {
  kind: "album";
  album: AlbumSummary;
  artists: ArtistRef[];
}

export interface SearchItemArtist {
  kind: "artist";
  id: string;
  name: string;
  thumbnails: Thumbnail[];
}

export interface SearchItemPlaylist {
  kind: "playlist";
  id: string;
  title: string;
  author: string | null;
  itemCount: number | null;
  thumbnails: Thumbnail[];
}

export interface SearchItemPodcast {
  kind: "podcast";
  id: string;
  title: string;
  author: string | null;
  thumbnails: Thumbnail[];
}

export interface SearchItemSong {
  kind: "song";
  song: Song;
  video: boolean;
}

export type SearchItem =
  | SearchItemAlbum
  | SearchItemArtist
  | SearchItemPlaylist
  | SearchItemPodcast
  | SearchItemSong;

export interface SearchSection {
  title: string;
  type: SearchType | null;
  items: SearchItem[];
}

export interface SearchPage {
  sections: SearchSection[];
}

export interface Episode {
  song: Song;
  date: string | null;
  description: string | null;
}

export interface PodcastPage {
  id: string;
  title: string;
  author: string | null;
  description: string | null;
  thumbnails: Thumbnail[];
  episodes: Episode[];
}

export interface HomeSection {
  title: string;
  items: SearchItem[];
}

export interface HomePage {
  sections: HomeSection[];
}

export interface SuggestionsResponse {
  items: string[];
}
